version: '3.1'
services:
  dashy:
    image: lissy93/dashy
    volumes:
      - ./dashy:/config
    ports:
      - 8080:80

  metabase:
    image: metabase/metabase
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - 3000:3000

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 81:81
      - 443:443

  meshcentral:
    image: meshcentral/meshcentral
    volumes:
      - ./meshcentral-data:/home/node/meshcentral/meshcentral-data
    ports:
      - 444:444

  vaultwarden:
    image: vaultwarden/server
    volumes:
      - ./vaultwarden-data:/data
    ports:
      - 3012:3012

  remotely:
    image: remotely/remote
    volumes:
      - ./remotely-data:/app/Remotely_Data
    ports:
      - 5000:5000

  guacamole:
    image: oznu/guacamole
    volumes:
      - ./guacamole-data:/config
    ports:
      - 8081:8080

  pihole:
    image: pihole/pihole
    volumes:
      - ./pihole-data:/etc/pihole/
      - ./pihole-dnsmasq:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp

  pi-alert:
    image: pialert/pialert
    volumes:
      - ./pialert-data:/db
    ports:
      - 8888:8888

  speedtest-tracker:
    image: henrywhitaker3/speedtest-tracker
    volumes:
      - ./speedtest-data:/config
    ports:
      - 8765:80

  uptime-kuma:
    image: louislam/uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data/
    ports:
      - 3001:3001

  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - ./homeassistant-data:/config
